version: '3.9'
services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - nodejs
  nodejs:
    image: node:15.3.0-alpine3.12
    user: "node"
    working_dir: /home/node/app
    expose:
      - 8080
    volumes:
      - ./code:/home/node/app
    command: "npm start"
