---
- name: webserver deployment
  hosts: webserver
  become: true
  become_method: sudo
  tasks:
    - name: "Apt-get update"
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: "Install nodejs"
      apt:
        name: ['nodejs']
        state: latest



